### ISSUE TITLE
New Lotus map not showing

### ISSUE THREAD

**Issue by cybermodz** [PenguinDevs/ValoRPC#1]
Running the tool and lotus map not showing.

![image](https://github.com/PenguinDevs/ValoRPC/assets/39441384/6f19e863-9851-44aa-bfb7-4677298e5f99)

**Comment by PenguinDevs** [comment]
Hey, apologies for the late reply! It's been a while since I've visited this repo.

Unfortunately, there isn't any way to automatically use the images of new characters and maps from only the client's side of this application.

As there isn't any API available on Discord's end to upload images to the 'rich presence assets', I am pretty much left with the only option to upload these images manually-- which I no longer keep up with the game updates anymore :(

I've uploaded the images for the new maps Piazza, Kasbah, District, Lotus, as well as the new Deadlock character.

Additionally, the new team deathmatch game mode is now supported in [this version of ValoRPC.](https://github.com/PenguinDevs/ValoRPC/releases/tag/v0.2.4-alpha)
